spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:${MYSQL_PORT}/mentoring?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: mentoring
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
    bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}

config:
  client:
    origin: ${DOMAIN_IP}
  jwt:
    secret: ${JWT_SECRET}


server:
  port: 8080
